(function(){var k,l=this;
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function n(a){return"string"==typeof a}function p(a){return"function"==m(a)}function aa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ba="closure_uid_"+(1E9*Math.random()>>>0),ca=0;function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return q.apply(null,arguments)}var fa=Date.now||function(){return+new Date};
function r(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function s(a,b){function c(){}c.prototype=b.prototype;a.s=b.prototype;a.prototype=new c;a.H=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function ga(){0!=ha&&(this[ba]||(this[ba]=++ca))}var ha=0;function t(a){if(Error.captureStackTrace)Error.captureStackTrace(this,t);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}s(t,Error);t.prototype.name="CustomError";function u(a,b){return a<b?-1:a>b?1:0};var v=Array.prototype,ia=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(n(a))return n(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ja=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};var w;a:{var ka=l.navigator;if(ka){var la=ka.userAgent;if(la){w=la;break a}}w=""};var ma=-1!=w.indexOf("Opera")||-1!=w.indexOf("OPR"),x=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),y=-1!=w.indexOf("Gecko")&&-1==w.toLowerCase().indexOf("webkit")&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE")),z=-1!=w.toLowerCase().indexOf("webkit");function na(){var a=l.document;return a?a.documentMode:void 0}
var oa=function(){var a="",b;if(ma&&l.opera)return a=l.opera.version,p(a)?a():a;y?b=/rv\:([^\);]+)(\)|;)/:x?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:z&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(w))?a[1]:"");return x&&(b=na(),b>parseFloat(a))?String(b):a}(),pa={};
function A(a){var b;if(!(b=pa[a])){b=0;for(var c=String(oa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",D=RegExp("(\\d*)(\\D*)","g"),E=RegExp("(\\d*)(\\D*)","g");do{var F=D.exec(g)||["","",""],G=E.exec(h)||["","",""];if(0==F[0].length&&0==G[0].length)break;b=u(0==F[1].length?0:parseInt(F[1],10),0==G[1].length?0:parseInt(G[1],10))||u(0==F[2].length,0==G[2].length)||
u(F[2],G[2])}while(0==b)}b=pa[a]=0<=b}return b}var qa=l.document,ra=qa&&x?na()||("CSS1Compat"==qa.compatMode?parseInt(oa,10):5):void 0;var B;(B=!x)||(B=x&&9<=ra);var sa=B,ta=x&&!A("9");!z||A("528");y&&A("1.9b")||x&&A("8")||ma&&A("9.5")||z&&A("528");y&&!A("8")||x&&A("9");function C(a,b){this.type=a;this.a=this.b=b}C.prototype.c=function(){};function H(a){H[" "](a);return a}H[" "]=function(){};function I(a,b){C.call(this,a?a.type:"");this.d=this.a=this.b=null;if(a){this.type=a.type;this.b=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&y)try{H(c.nodeName)}catch(d){}this.d=a;a.defaultPrevented&&this.c()}}s(I,C);I.prototype.c=function(){I.s.c.call(this);var a=this.d;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ta)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var J="closure_listenable_"+(1E6*Math.random()|0),ua=0;function va(a,b,c,d,e){this.h=a;this.proxy=null;this.src=b;this.type=c;this.m=!!d;this.n=e;++ua;this.removed=this.l=!1}function wa(a){a.removed=!0;a.h=null;a.proxy=null;a.src=null;a.n=null};var xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ya(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<xa.length;f++)c=xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function K(a){this.src=a;this.a={};this.b=0}function za(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.b++);var g=Aa(b,c,d,e);-1<g?(a=b[g],a.l=!1):(a=new va(c,a.src,f,!!d,e),a.l=!1,b.push(a));return a}K.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Aa(e,b,c,d);return-1<b?(wa(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function Ba(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=ia(d,b),f;(f=0<=e)&&v.splice.call(d,e,1);f&&(wa(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}function Aa(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.h==b&&f.m==!!c&&f.n==d)return e}return-1};var Ca="closure_lm_"+(1E6*Math.random()|0),Da={},Ea=0;function Fa(a,b,c,d,e){if("array"==m(b))for(var f=0;f<b.length;f++)Fa(a,b[f],c,d,e);else if(c=Ga(c),a&&a[J])a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=L(a);g||(a[Ca]=g=new K(a));c=za(g,b,c,d,e);c.proxy||(d=Ha(),c.proxy=d,d.src=a,d.h=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Ia(b.toString()),d),Ea++)}}
function Ha(){var a=Ja,b=sa?function(c){return a.call(b.src,b.h,c)}:function(c){c=a.call(b.src,b.h,c);if(!c)return c};return b}function Ka(a,b,c,d,e){if("array"==m(b))for(var f=0;f<b.length;f++)Ka(a,b[f],c,d,e);else(c=Ga(c),a&&a[J])?a.k.remove(String(b),c,d,e):a&&(a=L(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Aa(b,c,!!d,e)),(c=-1<a?b[a]:null)&&La(c))}
function La(a){if("number"!=typeof a&&a&&!a.removed){var b=a.src;if(b&&b[J])Ba(b.k,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.m):b.detachEvent&&b.detachEvent(Ia(c),d);Ea--;(c=L(b))?(Ba(c,a),0==c.b&&(c.src=null,b[Ca]=null)):wa(a)}}}function Ia(a){return a in Da?Da[a]:Da[a]="on"+a}function Ma(a,b,c,d){var e=1;if(a=L(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.m==c&&!f.removed&&(e&=!1!==Na(f,d))}return Boolean(e)}
function Na(a,b){var c=a.h,d=a.n||a.src;a.l&&La(a);return c.call(d,b)}
function Ja(a,b){if(a.removed)return!0;if(!sa){var c;if(!(c=b))a:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new I(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--)c.a=e[h],d&=Ma(e[h],f,!0,c);for(h=0;h<e.length;h++)c.a=e[h],d&=Ma(e[h],f,!1,c)}return d}return Na(a,
new I(b,this))}function L(a){a=a[Ca];return a instanceof K?a:null}var Oa="__closure_events_fn_"+(1E9*Math.random()>>>0);function Ga(a){return p(a)?a:a[Oa]||(a[Oa]=function(b){return a.handleEvent(b)})};function M(){ga.call(this);this.k=new K(this);this.e=this}s(M,ga);M.prototype[J]=!0;M.prototype.addEventListener=function(a,b,c,d){Fa(this,a,b,c,d)};M.prototype.removeEventListener=function(a,b,c,d){Ka(this,a,b,c,d)};M.prototype.listen=function(a,b,c,d){return za(this.k,String(a),b,c,d)};function Pa(a,b,c,d){if(b=a.k.a[String(b)]){b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.m==c){var h=g.h,D=g.n||g.src;g.l&&Ba(a.k,g);e=!1!==h.call(D,d)&&e}}}};function N(a,b,c){this.c=a;this.b=b;this.a=c;this.id=this.b+(this.a?"-"+this.a:"")}N.prototype.send=function(a,b){var c=new O(a),d=this.a;c.f=this.b;c.g=d;b&&(c.b=b);var d=c.d,e=this.c,f=c.toJSON();Qa(e).postMessage(f);e.a.push(c);50<e.a.length&&(e.a.length-=1);return d};function Ra(a){C.call(this,a.req||"event")}s(Ra,C);function Sa(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function Ta(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function Ua(a){l.setTimeout(function(){throw a;},0)}var Va;
function Wa(){if(l.Promise&&l.Promise.resolve){var a=l.Promise.resolve();return function(b){a.then(function(){try{b()}catch(a){Ua(a)}})}}var b=l.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+
"//"+b.location.host,a=q(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.t;d.t=null;a()};return function(a){e.next={t:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};function Xa(a,b){if(!Ya){var c=Za;p(l.setImmediate)?l.setImmediate(c):(Va||(Va=Wa()),Va(c));Ya=!0}P.push(new $a(a,b))}var Ya=!1,P=[];function Za(){for(;P.length;){var a=P;P=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Ua(d)}}}Ya=!1}function $a(a,b){this.a=a;this.b=b};function Q(a,b){this.b=R;this.f=void 0;this.a=this.e=null;this.c=this.d=!1;try{var c=this;a.call(b,function(a){S(c,T,a)},function(a){S(c,U,a)})}catch(d){S(this,U,d)}}var R=0,T=2,U=3;Q.prototype.then=function(a,b,c){return ab(this,p(a)?a:null,p(b)?b:null,c)};Sa(Q);function bb(a,b){a.a&&a.a.length||a.b!=T&&a.b!=U||cb(a);a.a||(a.a=[]);a.a.push(b)}
function ab(a,b,c,d){var e={q:null,v:null,w:null};e.q=new Q(function(a,g){e.v=b?function(c){try{var e=b.call(d,c);a(e)}catch(E){g(E)}}:a;e.w=c?function(b){try{var e=c.call(d,b);a(e)}catch(E){g(E)}}:g});e.q.e=a;bb(a,e);return e.q}Q.prototype.g=function(a){this.b=R;S(this,T,a)};Q.prototype.j=function(a){this.b=R;S(this,U,a)};
function S(a,b,c){if(a.b==R){if(a==c)b=U,c=new TypeError("Promise cannot resolve to itself");else{if(Ta(c)){a.b=1;c.then(a.g,a.j,a);return}if(aa(c))try{var d=c.then;if(p(d)){db(a,c,d);return}}catch(e){b=U,c=e}}a.f=c;a.b=b;cb(a);b!=U||eb(a,c)}}function db(a,b,c){function d(b){f||(f=!0,a.j(b))}function e(b){f||(f=!0,a.g(b))}a.b=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function cb(a){a.d||(a.d=!0,Xa(a.o,a))}
Q.prototype.o=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++){var c=a[b],d=this.f;if(this.b==T)c.v(d);else{for(var e=void 0,e=this;e&&e.c;e=e.e)e.c=!1;c.w(d)}}}this.d=!1};function eb(a,b){a.c=!0;Xa(function(){a.c&&fb.call(null,b)})}var fb=Ua;/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function V(a,b){this.e=[];this.G=b||null;this.a=this.c=!1;this.d=void 0;this.o=this.D=this.g=!1;this.f=0;this.j=null;this.F=0}k=V.prototype;k.u=function(a,b){this.g=!1;gb(this,a,b)};function gb(a,b,c){a.c=!0;a.d=c;a.a=!b;hb(a)}function ib(a){if(a.c){if(!a.o)throw new W;a.o=!1}}k.callback=function(a){ib(this);gb(this,!0,a)};k.r=function(a){ib(this);gb(this,!1,a)};k.B=function(a,b){return this.i(a,null,b)};k.C=function(a,b){return this.i(null,a,b)};k.A=function(a,b){return this.i(a,a,b)};
k.i=function(a,b,c){this.e.push([a,b,c]);this.c&&hb(this);return this};k.then=function(a,b,c){var d,e,f=new Q(function(a,b){d=a;e=b});this.i(d,function(a){e(a)});return f.then(a,b,c)};Sa(V);function jb(a){return ja(a.e,function(a){return p(a[1])})}
function hb(a){if(a.f&&a.c&&jb(a)){var b=a.f,c=X[b];c&&(l.clearTimeout(c.p),delete X[b]);a.f=0}a.j&&(a.j.F--,delete a.j);for(var b=a.d,d=c=!1;a.e.length&&!a.g;){var e=a.e.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var h=f.call(e||a.G,b);void 0!==h&&(a.a=a.a&&(h==b||h instanceof Error),a.d=b=h);Ta(b)&&(d=!0,a.g=!0)}catch(D){b=D,a.a=!0,jb(a)||(c=!0)}}a.d=b;d&&(h=q(a.u,a,!0),d=q(a.u,a,!1),b instanceof V?(b.i(h,d),b.D=!0):b.then(h,d));c&&(b=new kb(b),X[b.p]=b,a.f=b.p)}function W(){t.call(this)}
s(W,t);W.prototype.message="Deferred has already fired";W.prototype.name="AlreadyCalledError";function kb(a){this.p=l.setTimeout(q(this.b,this),0);this.a=a}kb.prototype.b=function(){delete X[this.p];throw this.a;};var X={};function Y(a,b){V.call(this,0,b);this.b=[]}s(Y,V);Y.prototype.callback=function(a){this.b.length=0;Y.s.callback.call(this,a)};Y.prototype.r=function(a){this.b.length=0;Y.s.r.call(this,a)};function O(a){lb++;this.id="i"+lb;this.req=a;this.c=!0;this.a=this.b=null;this.d=new Y;this.e=NaN}var lb=0;
O.prototype.listen=function(a){if(a&&a.id==this.id){this.b=a.data;var b=a.error;b&&(b instanceof Error?this.a=b:aa(b)?(this.a=Error(b.message),this.a.name=b.name,this.a.source=b,this.a.result=this.b):(this.a=Error(b),this.a.name="UnknownError"));if(a.done)this.c=!1,this.a?this.d.r(this.a):this.d.callback(this.b),window.clearTimeout(this.e);else{b=this.d;a=a.data;for(var c=0;c<b.b.length;c++)b.b[c][0].call(b.b[c][1],a)}return!0}return!1};
O.prototype.toString=function(){return"Message:"+this.id+(this.c?"*":"")};O.prototype.toJSON=function(){var a=this;this.e=window.setTimeout(function(){if(a.c){var b=Error("message timeout");b.name="TimeOutError";a.listen({id:a.id,req:a.req,error:b})}},1E4);return{id:this.id,req:this.req,group:this.f,name:this.g,data:this.b}};function Z(a){M.call(this);var b=n(a)?null:a;this.name=n(a)?a:a.name;this.a=[];this.g=b;this.b=null;this.c={}}s(Z,M);
Z.prototype.f=function(a){if(a)if(a.id)for(var b=this.a.length-1;0<=b;b--){if(this.a[b].id==a.id){if(this.a[b].listen(a)){this.a[b].c?25<b&&(b=this.a.splice(b,1),this.a.unshift(b[0])):this.a.splice(b,1);break}break}}else if("info"==a.req)a.data=this.g,this.b.postMessage(a);else if("html-body-inner"==a.req)window.console.log("html",a),a.req="",a.done=!0,a.data=document&&document.body?document.body.innerHTML:"",this.b.postMessage(a);else{b=this.e;a=new Ra(a);var c=a.type||a;if(n(a))a=new C(a,b);else if(a instanceof
C)a.b=a.b||b;else{var d=a;a=new C(c,b);ya(a,d)}b=a.a=b;Pa(b,c,!0,a);Pa(b,c,!1,a)}};Z.prototype.toString=function(){return"Pipe:"+this.name};Z.prototype.d=function(a,b){var c=a||mb,d=c+(b?"-"+b:"");this.c[d]||(this.c[d]=new N(this,c,b||""));return this.c[d]};function Qa(a){if(!a.b){a.b=chrome.runtime.connect({name:a.name});var b=q(a.f,a);a.b.onMessage.addListener(b);a.b.onDisconnect.addListener(function(){a.b.onMessage.removeListener(b);a.b=null;a.a.length=0})}return a.b}var $=null,mb="default";r("ydn.msg.Pipe",Z);r("ydn.msg.initPipe",function(a){var b=a;n(a)&&(b={group:a,name:a+"-"+fa()});return $=new Z(b)});r("ydn.msg.getChannel",function(a,b){if(!$){var c=mb+"-"+fa();$=new Z(c)}return $.d(a,b)});Z.prototype.listen=Z.prototype.listen;Z.prototype.getChannel=Z.prototype.d;N.prototype.send=N.prototype.send;r("goog.async.Deferred",V);V.prototype.addCallback=V.prototype.B;V.prototype.addErrback=V.prototype.C;V.prototype.addBoth=V.prototype.A;V.prototype.addCallbacks=V.prototype.i;})();
