(function(){var k,l=this;
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function n(a){return"string"==typeof a}function p(a){return"function"==m(a)}function q(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function r(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return r.apply(null,arguments)}var ea=Date.now||function(){return+new Date};
function s(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function t(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.I=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function fa(){0!=ga&&(this[aa]||(this[aa]=++ba))}var ga=0;function u(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}t(u,Error);u.prototype.name="CustomError";function v(a,b){return a<b?-1:a>b?1:0};var w=Array.prototype,ha=w.indexOf?function(a,b,c){return w.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(n(a))return n(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ia=w.some?function(a,b,c){return w.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
function ja(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var x;a:{var ka=l.navigator;if(ka){var la=ka.userAgent;if(la){x=la;break a}}x=""};var ma=-1!=x.indexOf("Opera")||-1!=x.indexOf("OPR"),y=-1!=x.indexOf("Trident")||-1!=x.indexOf("MSIE"),z=-1!=x.indexOf("Gecko")&&-1==x.toLowerCase().indexOf("webkit")&&!(-1!=x.indexOf("Trident")||-1!=x.indexOf("MSIE")),A=-1!=x.toLowerCase().indexOf("webkit");function na(){var a=l.document;return a?a.documentMode:void 0}
var oa=function(){var a="",b;if(ma&&l.opera)return a=l.opera.version,p(a)?a():a;z?b=/rv\:([^\);]+)(\)|;)/:y?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:A&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(x))?a[1]:"");return y&&(b=na(),b>parseFloat(a))?String(b):a}(),pa={};
function B(a){var b;if(!(b=pa[a])){b=0;for(var c=String(oa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",D=RegExp("(\\d*)(\\D*)","g"),E=RegExp("(\\d*)(\\D*)","g");do{var F=D.exec(g)||["","",""],G=E.exec(h)||["","",""];if(0==F[0].length&&0==G[0].length)break;b=v(0==F[1].length?0:parseInt(F[1],10),0==G[1].length?0:parseInt(G[1],10))||v(0==F[2].length,0==G[2].length)||
v(F[2],G[2])}while(0==b)}b=pa[a]=0<=b}return b}var qa=l.document,ra=qa&&y?na()||("CSS1Compat"==qa.compatMode?parseInt(oa,10):5):void 0;var C;(C=!y)||(C=y&&9<=ra);var sa=C,ta=y&&!B("9");!A||B("528");z&&B("1.9b")||y&&B("8")||ma&&B("9.5")||A&&B("528");z&&!B("8")||y&&B("9");function H(a,b){this.type=a;this.a=this.b=b}H.prototype.c=function(){};function I(a){I[" "](a);return a}I[" "]=function(){};function J(a,b){H.call(this,a?a.type:"");this.d=this.a=this.b=null;if(a){this.type=a.type;this.b=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&z)try{I(c.nodeName)}catch(d){}this.d=a;a.defaultPrevented&&this.c()}}t(J,H);J.prototype.c=function(){J.t.c.call(this);var a=this.d;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ta)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var ua="closure_listenable_"+(1E6*Math.random()|0);function va(a){try{return!(!a||!a[ua])}catch(b){return!1}}var wa=0;function xa(a,b,c,d,e){this.h=a;this.proxy=null;this.src=b;this.type=c;this.b=!!d;this.c=e;++wa;this.a=this.n=!1}function ya(a){a.a=!0;a.h=null;a.proxy=null;a.src=null;a.c=null};var za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Aa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<za.length;f++)c=za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function K(a){this.src=a;this.a={};this.b=0}function Ba(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.b++);var g=Ca(b,c,d,e);-1<g?(a=b[g],a.n=!1):(a=new xa(c,a.src,f,!!d,e),a.n=!1,b.push(a));return a}K.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Ca(e,b,c,d);return-1<b?(ya(e[b]),w.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function Da(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=ha(d,b),f;(f=0<=e)&&w.splice.call(d,e,1);f&&(ya(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}function Ca(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.a&&f.h==b&&f.b==!!c&&f.c==d)return e}return-1};var Ea="closure_lm_"+(1E6*Math.random()|0),Fa={},Ga=0;function Ha(a,b,c,d,e){if("array"==m(b))for(var f=0;f<b.length;f++)Ha(a,b[f],c,d,e);else if(c=Ia(c),va(a))a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=L(a);g||(a[Ea]=g=new K(a));c=Ba(g,b,c,d,e);c.proxy||(d=Ja(),c.proxy=d,d.src=a,d.h=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Ka(b.toString()),d),Ga++)}}
function Ja(){var a=La,b=sa?function(c){return a.call(b.src,b.h,c)}:function(c){c=a.call(b.src,b.h,c);if(!c)return c};return b}function Ma(a,b,c,d,e){if("array"==m(b))for(var f=0;f<b.length;f++)Ma(a,b[f],c,d,e);else(c=Ia(c),va(a))?a.l.remove(String(b),c,d,e):a&&(a=L(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Ca(b,c,!!d,e)),(c=-1<a?b[a]:null)&&Na(c))}
function Na(a){if("number"!=typeof a&&a&&!a.a){var b=a.src;if(va(b))Da(b.l,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.b):b.detachEvent&&b.detachEvent(Ka(c),d);Ga--;(c=L(b))?(Da(c,a),0==c.b&&(c.src=null,b[Ea]=null)):ya(a)}}}function Ka(a){return a in Fa?Fa[a]:Fa[a]="on"+a}function Oa(a,b,c,d){var e=1;if(a=L(a))if(b=a.a[b.toString()])for(b=ja(b),a=0;a<b.length;a++){var f=b[a];f&&f.b==c&&!f.a&&(e&=!1!==Pa(f,d))}return Boolean(e)}
function Pa(a,b){var c=a.h,d=a.c||a.src;a.n&&Na(a);return c.call(d,b)}
function La(a,b){if(a.a)return!0;if(!sa){var c;if(!(c=b))a:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new J(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--)c.a=e[h],d&=Oa(e[h],f,!0,c);for(h=0;h<e.length;h++)c.a=e[h],d&=Oa(e[h],f,!1,c)}return d}return Pa(a,
new J(b,this))}function L(a){a=a[Ea];return a instanceof K?a:null}var Qa="__closure_events_fn_"+(1E9*Math.random()>>>0);function Ia(a){return p(a)?a:a[Qa]||(a[Qa]=function(b){return a.handleEvent(b)})};function M(){fa.call(this);this.l=new K(this);this.e=this}t(M,fa);M.prototype[ua]=!0;M.prototype.addEventListener=function(a,b,c,d){Ha(this,a,b,c,d)};M.prototype.removeEventListener=function(a,b,c,d){Ma(this,a,b,c,d)};M.prototype.listen=function(a,b,c,d){return Ba(this.l,String(a),b,c,d)};function Ra(a,b,c,d){if(b=a.l.a[String(b)]){b=ja(b);for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.a&&g.b==c){var h=g.h,D=g.c||g.src;g.n&&Da(a.l,g);e=!1!==h.call(D,d)&&e}}}};function Sa(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function Ta(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function Ua(a){p(l.setImmediate)?l.setImmediate(a):(Va||(Va=Wa()),Va(a))}var Va;
function Wa(){if(l.u&&l.u.resolve){var a=l.u.resolve();return function(b){a.then(b)}}var b=l.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==
d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.v;d.v=null;a()};return function(a){e.next={v:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=
null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};function Xa(a){Ua(function(){throw a;})}function Ya(a,b){Za||(Ua($a),Za=!0);N.push(new ab(a,b))}var Za=!1,N=[];function $a(){for(;N.length;){var a=N;N=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Xa(d)}}}Za=!1}function ab(a,b){this.a=a;this.b=b};function O(a,b){this.a=P;this.f=void 0;this.b=this.e=null;this.c=this.d=!1;this.g=[];bb(this,Error("created"));this.j=0;try{var c=this;a.call(b,function(a){Q(c,R,a)},function(a){Q(c,S,a)})}catch(d){Q(this,S,d)}}var P=0,R=2,S=3;O.prototype.then=function(a,b,c){bb(this,Error("then"));return cb(this,p(a)?a:null,p(b)?b:null,c)};Sa(O);function db(a,b){a.b&&a.b.length||a.a!=R&&a.a!=S||eb(a);a.b||(a.b=[]);a.b.push(b)}
function cb(a,b,c,d){var e={q:null,A:null,B:null};e.q=new O(function(a,g){e.A=b?function(c){try{var e=b.call(d,c);a(e)}catch(E){g(E)}}:a;e.B=c?function(b){try{var e=c.call(d,b);a(e)}catch(E){g(E)}}:g});e.q.e=a;db(a,e);return e.q}O.prototype.k=function(a){this.a=P;Q(this,R,a)};O.prototype.m=function(a){this.a=P;Q(this,S,a)};
function Q(a,b,c){if(a.a==P){if(a==c)b=S,c=new TypeError("Promise cannot resolve to itself");else{if(Ta(c)){a.a=1;c.then(a.k,a.m,a);return}if(q(c))try{var d=c.then;if(p(d)){fb(a,c,d);return}}catch(e){b=S,c=e}}a.f=c;a.a=b;eb(a);b!=S||gb(a,c)}}function fb(a,b,c){function d(b){f||(f=!0,a.m(b))}function e(b){f||(f=!0,a.k(b))}a.a=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function eb(a){a.d||(a.d=!0,Ya(a.s,a))}
O.prototype.s=function(){for(;this.b&&this.b.length;){var a=this.b;this.b=[];for(var b=0;b<a.length;b++){this.j++;var c=a[b],d=this.f;if(this.a==R)c.A(d);else{for(var e=void 0,e=this;e&&e.c;e=e.e)e.c=!1;c.B(d)}}}this.d=!1};function bb(a,b){if(n(b.stack)){var c=b.stack.split("\n",4)[3],d=b.message,d=d+Array(11-d.length).join(" ");a.g.push(d+c)}}
function gb(a,b){a.c=!0;Ya(function(){if(a.c){if(b&&n(b.stack)&&a.g.length){for(var c=["Promise trace:"],d=a;d;d=d.e){for(var e=a.j;0<=e;e--)c.push(d.g[e]);c.push("Value: ["+(d.a==S?"REJECTED":"FULFILLED")+"] <"+String(d.f)+">")}b.stack+="\n\n"+c.join("\n")}hb.call(null,b)}})}var hb=Xa;/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function T(a,b){this.e=[];this.H=b||null;this.a=this.c=!1;this.d=void 0;this.m=this.s=this.g=!1;this.f=0;this.k=null;this.G=0;this.j=null;if(Error.captureStackTrace){var c={stack:""};Error.captureStackTrace(c,T);"string"==typeof c.stack&&(this.j=c.stack.replace(/^[^\n]*\n/,""))}}k=T.prototype;k.w=function(a,b){this.g=!1;ib(this,a,b)};function ib(a,b,c){a.c=!0;a.d=c;a.a=!b;jb(a)}function kb(a){if(a.c){if(!a.m)throw new U;a.m=!1}}k.p=function(a){kb(this);ib(this,!0,a)};
k.r=function(a){kb(this);lb(this,a);ib(this,!1,a)};function lb(a,b){a.j&&q(b)&&b.stack&&/^[^\n]+(\n   [^\n]+)+/.test(b.stack)&&(b.stack=b.stack+"\nDEFERRED OPERATION:\n"+a.j)}k.D=function(a,b){return this.i(a,null,b)};k.F=function(a,b){return this.i(null,a,b)};k.C=function(a,b){return this.i(a,a,b)};k.i=function(a,b,c){this.e.push([a,b,c]);this.c&&jb(this);return this};k.then=function(a,b,c){var d,e,f=new O(function(a,b){d=a;e=b});this.i(d,function(a){e(a)});return f.then(a,b,c)};Sa(T);
function mb(a){return ia(a.e,function(a){return p(a[1])})}
function jb(a){if(a.f&&a.c&&mb(a)){var b=a.f,c=V[b];c&&(l.clearTimeout(c.o),delete V[b]);a.f=0}a.k&&(a.k.G--,delete a.k);for(var b=a.d,d=c=!1;a.e.length&&!a.g;){var e=a.e.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var h=f.call(e||a.H,b);void 0!==h&&(a.a=a.a&&(h==b||h instanceof Error),a.d=b=h);Ta(b)&&(d=!0,a.g=!0)}catch(D){b=D,a.a=!0,lb(a,b),mb(a)||(c=!0)}}a.d=b;d&&(h=r(a.w,a,!0),d=r(a.w,a,!1),b instanceof T?(b.i(h,d),b.s=!0):b.then(h,d));c&&(b=new nb(b),V[b.o]=b,a.f=b.o)}
function U(){u.call(this)}t(U,u);U.prototype.message="Deferred has already fired";U.prototype.name="AlreadyCalledError";function nb(a){this.o=l.setTimeout(r(this.b,this),0);this.a=a}nb.prototype.b=function(){delete V[this.o];throw this.a;};var V={};function W(a,b){T.call(this,0,b);this.b=[]}t(W,T);W.prototype.p=function(a){this.b.length=0;W.t.p.call(this,a)};W.prototype.r=function(a){this.b.length=0;W.t.r.call(this,a)};function X(a){ob++;this.id="i"+ob;this.req=a;this.c=!0;this.a=this.b=null;this.d=new W;this.e=NaN}var ob=0;
X.prototype.listen=function(a){if(a&&a.id==this.id){this.b=a.data;var b=a.error;b&&(b instanceof Error?this.a=b:q(b)?(this.a=Error(b.message),this.a.name=b.name,this.a.source=b,this.a.result=this.b):(this.a=Error(b),this.a.name="UnknownError"));if(a.done)this.c=!1,this.a?this.d.r(this.a):this.d.p(this.b),window.clearTimeout(this.e);else{b=this.d;a=a.data;for(var c=0;c<b.b.length;c++)b.b[c][0].call(b.b[c][1],a)}return!0}return!1};
X.prototype.toString=function(){return"Message:"+this.id+(this.c?"*":"")};X.prototype.toJSON=function(){var a=this;this.e=window.setTimeout(function(){if(a.c){var b=Error("message timeout");b.name="TimeOutError";a.listen({id:a.id,req:a.req,error:b})}},1E4);return{id:this.id,req:this.req,group:this.f,name:this.g,data:this.b}};function Y(a){M.call(this);var b=n(a)?null:a;this.name=n(a)?a:a.name;this.a=[];this.g=b;this.b=null;this.c={}}t(Y,M);function pb(a){H.call(this,"post");this.message=a}t(pb,H);
Y.prototype.f=function(a){if(a)if(a.id)for(var b=this.a.length-1;0<=b;b--){if(this.a[b].id==a.id&&this.a[b].listen(a)){this.a[b].c?25<b&&(b=this.a.splice(b,1),this.a.unshift(b[0])):this.a.splice(b,1);break}}else if("info"==a.req)a.data=this.g,this.b.postMessage(a);else if("html-body-inner"==a.req)window.console.log("html",a),a.req="",a.done=!0,a.data=document&&document.body?document.body.innerHTML:"",this.b.postMessage(a);else{b=this.e;a=new pb(a);var c=a.type||a;if(n(a))a=new H(a,b);else if(a instanceof
H)a.b=a.b||b;else{var d=a;a=new H(c,b);Aa(a,d)}b=a.a=b;Ra(b,c,!0,a);Ra(b,c,!1,a)}};Y.prototype.toString=function(){return"Pipe:"+this.name};Y.prototype.d=function(a,b){var c=a||qb,d=c+(b?"-"+b:"");this.c[d]||(this.c[d]=new Z(this,c,b||""));return this.c[d]};function rb(a){if(!a.b){a.b=chrome.runtime.connect({name:a.name});var b=r(a.f,a);a.b.onMessage.addListener(b);a.b.onDisconnect.addListener(function(){a.b.onMessage.removeListener(b);a.b=null;a.a.length=0})}return a.b}var $=null,qb="default";
function Z(a,b,c){this.a=a;this.b=b;this.c=c}Z.prototype.d=function(a,b){var c=new X(a),d=this.c;c.f=this.b;c.g=d;b&&(c.b=b);var d=c.d,e=this.a,f=c.toJSON();rb(e).postMessage(f);e.a.push(c);50<e.a.length&&(e.a.length-=1);return d};s("ydn.msg.Pipe",Y);s("ydn.msg.initPipe",function(a){var b=a;n(a)&&(b={group:a,name:a+"-"+ea()});return $=new Y(b)});s("ydn.msg.getChannel",function(a,b){if(!$){var c=qb+"-"+ea();$=new Y(c)}return $.d(a,b)});Y.prototype.listen=Y.prototype.listen;Y.prototype.getChannel=Y.prototype.d;Z.prototype.send=Z.prototype.d;s("goog.async.Deferred",T);T.prototype.addCallback=T.prototype.D;T.prototype.addErrback=T.prototype.F;T.prototype.addBoth=T.prototype.C;T.prototype.addCallbacks=T.prototype.i;})();
